### ISSUE TITLE
display solar times on page stylized with bulma.io

### ISSUE THREAD

**Issue by TechnicalParadox** [TechnicalParadox/cbc-group2-project1#12]
12.3.20 - solar times are displayed in middle of page, we need to implement the animated cards to slide in from both sides and from the top that will allow the application time to load the solar time data.

solar times are currently just logged to console. We need to display them on the screen. Possibly have them fade in with some animation, this would give the site time to load data from the APIs before having to display to the user

**Comment by Gintstir** [comment]
12-4-20 : I put the solar times in their own cards that display in a newly created section below the hero.  These cards are not animated but I can look into doing that if we want.
